language: java
jdk:
  - oraclejdk7
  - oraclejdk8
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
install: travis_retry bundle install
script: bundle exec rake cucumber
after_success:
  - mvn test jacoco:report coveralls:jacoco
